owner: alanmuskproject
repo: health

sites:
  - name: Alan Site
    url: https://alanmusk.com
  - name: Alan API
    url: https://api.analmusk.com/api-docs/
  - name: Alan CDN
    url: https://cdn.analmusk.com

status-website:
  cname: health.alanmusk.com
  logoUrl: https://alanmusk.com/assets/logo.svg
  name: Alan Health
  introTitle: "**AlanMusk** health page."
  introMessage: Status page for AlanMusk
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  footer: "© <!-- -->2022<!-- --> AlanMusk"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
