owner: analmusk
repo: health

sites:
  - name: Anal Site
    url: https://analmusk.com
  - name: Alan Site
    url: https://alanmusk.com
  - name: Anal API
    url: https://api.analmusk.com/api-docs/
  - name: Anal CDN
    url: https://cdn.analmusk.com

status-website:
  cname: health.analmusk.com
  logoUrl: https://analmusk.com/assets/logo.svg
  name: Anal Health
  introTitle: "**AnalMusk** health page."
  introMessage: Status page for AnalMusk
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
